// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7zG3tYO7ZzWUa_ze5qCgNczHIPKSDGrY',
    appId: '1:514826786294:web:0aecca173ff9a3aef2e3d7',
    messagingSenderId: '514826786294',
    projectId: 'ecommerce-app-43c51',
    authDomain: 'ecommerce-app-43c51.firebaseapp.com',
    databaseURL: 'https://ecommerce-app-43c51-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-43c51.appspot.com',
    measurementId: 'G-484RNPR6TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARF4OYqpK618ooto_2WcALOC3W4tluZxM',
    appId: '1:514826786294:android:e8d62fe57de0721af2e3d7',
    messagingSenderId: '514826786294',
    projectId: 'ecommerce-app-43c51',
    databaseURL: 'https://ecommerce-app-43c51-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-43c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm03ZKSOv_jW1XA2MY9fbIQGyo9z6LNCk',
    appId: '1:514826786294:ios:bc8a345ed7483163f2e3d7',
    messagingSenderId: '514826786294',
    projectId: 'ecommerce-app-43c51',
    databaseURL: 'https://ecommerce-app-43c51-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-43c51.appspot.com',
    iosBundleId: 'com.example.hmrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm03ZKSOv_jW1XA2MY9fbIQGyo9z6LNCk',
    appId: '1:514826786294:ios:f3bd04b86f008a2ef2e3d7',
    messagingSenderId: '514826786294',
    projectId: 'ecommerce-app-43c51',
    databaseURL: 'https://ecommerce-app-43c51-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-43c51.appspot.com',
    iosBundleId: 'com.example.hmrent.RunnerTests',
  );
}
